Repository woocommerce/woocommerce-admin-test-helper, pull requests merged in 2021-04, with the labels that each got.

#8 Build script not working due to case issue in import
  package.json
  src/app/app.js
  src/app/index.js
  src/index.js
Labels: Ready to merge, type: bug

#12 Add ability to view & edit option content
  src/index.scss
  src/options/OptionEditor.js
  src/options/data/action-types.js
  src/options/data/actions.js
  src/options/data/reducer.js
  src/options/data/resolvers.js
  src/options/data/selectors.js
  src/options/index.js
Labels: Ready to review

#11 Add release script
  README.md
  bin/build-zip.sh
  bin/release-to-github.sh
  package.json
  woocommerce-admin-test-helper.php
Labels: Ready to review

#14 Add support for email notes and different note layouts
  api/admin-notes/add-note.php
  images/admin-notes/banner.jpg
  images/admin-notes/thumbnail.jpg
  images/admin-notes/woocommerce-logo-vector.png
  src/admin-notes/add-note.js
  src/index.scss
Labels: Ready to merge
